[project]
name = ""
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "distro>=1.9.0",
    "psutil>=6.1.1",
    "rich>=13.9.4",
    "screeninfo>=0.8.1",
]
